### ISSUE TITLE
Stock MSMTP Doesn't Work

### ISSUE THREAD

**Issue by joeyberkovitz** [tiredofit/docker-freepbx#18]
When using the MSMTP environment variables from the base image with gmail, configuration changes have to be made to get it to work:
`auto_from on` has to be added to /etc/msmtp
/etc/msmtp has to be owned by asterisk and permissions have to be set to 600

Please add an environment variable to support gmail with msmtp

**Comment by joeyberkovitz** [comment]
Added PR

**Comment by tiredofit** [comment]
Hi @joeyberkovitz - I appreciate you doing the legwork to get this working for others.
I closed the PR as I went about it in a bit of a different manner:
I've added the env var you recommended to the base images I maintain (alpine, debian, ubuntu) so that it can be used throughout all of my images. What I did keep though was the permissions modification to `/etc/msmtp` in this repo. I've got you marked in the Changelog for your addition for release 2.5.

Since I'm updating the base images, it will probably be a good day before Docker Hub gets around to building the new freepbx image. Thanks again!
