### ISSUE TITLE
** NO ISSUE** Thanks for the Docker

### ISSUE THREAD

**Issue by Brownster** [tiredofit/docker-freepbx#3]
Just wanted to say thanks for the Docker, i have written a little xml to help users run and manage this docker from within the unraid UI. I have it running haven't had chance to test it fully yet. But
 has to be one of the easiest ways of getting freepbx up and running

![freepbx docker 1](https://user-images.githubusercontent.com/6543166/34109275-f534791c-e3fa-11e7-960f-ba3eef2e219d.PNG)

![freepbx docker 2](https://user-images.githubusercontent.com/6543166/34109400-58569aca-e3fb-11e7-93fb-65957aff2967.PNG)

Thanks again

Marc

**Comment by tiredofit** [comment]
Fantastic News! Thanks for this. 
I'm a couple revisions away from being fully comfortable with this (I haven't yet moved it in a production mode yet myself) due to my modifications to let it run on a single database as I've noticed not all of the UCP modules fully work yet but I am definitely getting there. Enjoy!
