### ISSUE TITLE
Cant create new extension with voicemail?

### ISSUE THREAD

**Issue by Brownster** [tiredofit/docker-freepbx#4]
Hello,

I have successfully added a sipgate trunk but cant add a station with voicemail, should voicemail be available in this Docker image? Adding a station without VM works OK.

![freepbx issue](https://user-images.githubusercontent.com/6543166/34299982-e852fa18-e71d-11e7-8915-bfb5e0cb5f2a.PNG)

**Comment by tiredofit** [comment]
Yes, you should be able to. I believe there is a small quirk with permissions in the /etc/asterisk permission when you start it up the first time, and gets fixed after subsequent starts. Can you confirm that you've restarted it?

Also, you can enter inside the container and view the permissions of the /etc/asterisk directory. You will see many of them 'owned' by asterisk, and some 'root'. If so, that is the quirk that I am aware of. I'm just wrapping up one more docker image today (Jitsi Meet) for production and then I'll circle back to close this one once and for all.

**Comment by tiredofit** [comment]
I took a peek at it, and I've executed a `fwconsole chown` and a `chown -R asterisk /etc/asterisk` right before starting, so it appears its something inside of FreePBX which is not fully setting the permissions for the first time. Can confirm that on second boot that it resets itself nicely. The other alternative is what you could do is add to the cron script and put the following `0 * * * * chown -R asterisk /etc/asterisk >/dev/null 2>&1`inside the source of this image `/assets/cron/crontab.txt` and rebuild. This will reset the permissions each hour on the hour. If you simply try to map this file from outside your container already into the prebuilt image each time it boots it will add duplicate entries for the logrotation, which gives me an idea to update my base tiredofit/alpine, tiredofit/debian to seperate the core cron scripts to allow for users to add their own without impacting the base image, if that makes sense - Will do that over the holiday season.

**Comment by tiredofit** [comment]
New Base Images have been built. It'll take about 24 hours for Docker Hub to pick this up as it needs to go and rebuild every single one of my images with the new base. Once it's updated though for the short term you can do this instead of my previous comment:

Create a file `permissions.txt` outside of the container space, but map it to `/assets/cron-custom/permissions.txt` with the following content

````
0 * * * * chown -R asterisk /etc/asterisk >/dev/null 2>&1
````
Then upon container boot it should go about resetting the permissions if Freepbx somehow manages to break out of what it's supposed to do. Temporary solution for now, I'm more willing to bet I've done something silly here.
