### ISSUE TITLE
Error when open or close some RTP ports

### ISSUE THREAD

**Issue by rene-gomez** [tiredofit/docker-freepbx#43]
I used the docker-compose file example, but when i try to modify RTP ports the conainer never start up.

This is my RTP configuration:
```


   ports:
      - 18000-19999:18000-19999/udp
   environment:
      - RTP_START=18000
      - RTP_FINISH=19999
```

The console error is: 

> ERROR: for freepbx-app  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)
> ERROR: An HTTP request took too long to complete. Retry with --verbose to obtain debug information.
> If you encounter this issue regularly because of slow network conditions, consider setting COMPOSE_HTTP_TIMEOUT to a higher value (current value: 60).

If I try with the example ports 18000-18100 and exec the "docker ps", the result is:

`e4f5d090028a        tiredofit/freepbx                        "/init"                  18 seconds ago      Up 9 seconds        80/tcp, 443/tcp, 1025/tcp, 4569/tcp, 5060/tcp, 0.0.0.0:5060->5060/udp, 5160/tcp, 8001/tcp, 8003/tcp, 8008-8009/tcp, 8025/tcp, 0.0.0.0:5160->5160/udp, 10050/tcp, 0.0.0.0:4445->4445/tcp, 0.0.0.0:18000-18100->18000-18100/udp, 18101-20000/udp   freepbx-app`

You can see the 18101-20000 open ports.

I try change the RTP ports because the server work fine, I can connect extensions, but the calls don't have audio.

Please check that.

Best regards.

Rene

**Comment by tiredofit** [comment]
Can you try to see if just using 18000-18050 will make a difference? One thing that I found with Docker is that each port you expose it loads another process into memory, and you may be experiencing a memory condition.
Depending on how many extensions/concurrent calls you expect, you can tune your ports to a reasonable value.

**Comment by rene-gomez** [comment]
@tiredofit  I don't knew that, tks for the tip.

I can open from 18001 to 18030, but I can see the 18031 to 20000 open, how can I disable this?

`d06d29cc7c18        tiredofit/freepbx                        "/init"                  12 seconds ago      Up 6 seconds        80/tcp, 443/tcp, 1025/tcp, 4569/tcp, 5060/tcp, 0.0.0.0:5060->5060/udp, 5160/tcp, 8001/tcp, 8003/tcp, 8008-8009/tcp, 8025/tcp, 0.0.0.0:5160->5160/udp, 18000/udp, 10050/tcp, 0.0.0.0:4445->4445/tcp, 0.0.0.0:18001-18030->18001-18030/udp, 18031-20000/udp   freepbx-app`

**Comment by tiredofit** [comment]
In the Dockerfile I have exposed (which is a tad different then port mapping) 18000-20000/udp. Exposing doesn't do such funny things like creating new processes. You can verify to see if they are actually listening on your system by executing `netstat -tunap` and you'll see the ports that are actually public.

**Comment by rene-gomez** [comment]
Hi @tiredofit 

I consider necessary re-open this discussion, because is necessary close all ports from 18031-20000, even though this ports are open internally.

Best regards.

Rene

**Comment by tiredofit** [comment]
Hi Rene, since it is in the Docker build itself, if you needed to make a custom image that removed it you would have to fork it and change the ports inside its Dockerfile and rebuild it. I don't believe there is a way to "Un" expose the port after it is build as it is a part of the image itself. The purpose of exposing is for other containers to access those ports inside the container space that are a part of the same network. You will also see inside the container with the same `netstat -tunap` command that nothing is actually listening on them yet the port may be in an "open" state, however if you are not publishing the port ie with the `docker -p` or `ports:` directive in the docker-compose.yml noone will be able to access from the outside. As well if there is nothing listening on the port, it would fail to connect anyways.

**Comment by tiredofit** [comment]
Seems this has been a requested issue since 2013:
https://github.com/moby/moby/issues/2210
https://github.com/moby/moby/issues/8709

**Comment by rene-gomez** [comment]
I modify the dockerfile.

Best regards.

Rene
