### ISSUE TITLE
Image Tags

### ISSUE THREAD

**Issue by 0xQSL** [tiredofit/docker-freepbx#59]
Hi!
I was a bit confused by the image tags. 
Readme:
```
15 - Asterisk 16, Freepbx 15 - Debian Stretch
14 - Asterisk 14, Freepbx 14 - Debian Stretch
latest - Asterisk 16, Freepbx 15 - Debian Stretch 
```
https://hub.docker.com/r/tiredofit/freepbx/tags:
```
3.*
2.*
14-*
```
I'd suggest having either 15, 14 ... or 2, 3 ... 
It would also be nice to have 15 always be the newest release of the 15 image and have 15.x.y available for more specific versions like redis does for example: https://hub.docker.com/_/redis

**Comment by tiredofit** [comment]
Hi there. Yes, it could use a bit of work. A bit of this confusion came to be when we cut over to the breaking 15 release of Freepbx, where as before it followed the version numbers in the Changelog. I'll make some adjustments to this for you. One of the downsides to the Dockerhub Automatic Building is that each time you create a tag it actually creates a different version of the image entirely - so :latest would be different than 15:latest even though they are actually the same commit. So instead of caching the previous build it creates a new one, which Docker Hub tends to fail often when you are building multiple images especially ones that rely on compiling source like this one. I've been trying to massage it to get a NodeJS version compiled for weeks now with no such success.

**Comment by tiredofit** [comment]
Alright, so this is what I've done:
Master is no longer used.
A new branch `15` exists. Anytime a push happens it will create: `tiredofit/freepbx:{15,15-latest,latest,15-CHANGELOGVER}`
Same with `14`. Anytime a push happens it will create `tiredofit/freepbx:{14,14-latest,14-CHANGELOGVER}`
`Develop` will always push to `tiredofit/freepbx:develop`

Let's see if Dockerhub throws a fit on this new change :)

**Comment by tiredofit** [comment]
Seemed to work! Enjoy!
